name: GitHub Actions Build

on:
  push:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [GTASA]
        buildtype: [Release]

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build
      shell: cmd
      run: |
        set PLUGIN_SDK_DIR=plugin-sdk
        msbuild -m CLEO5.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
    - name: Pack binaries (Main)
      uses: ThirteenAG/zip-release@master
      with:
        path: ./.output/Release/*
        type: 'zip'
        filename: 'CLEO5.zip'
        exclusions: '*.pdb *.lib *.exp *.map'
    - name: Upload Release
      uses: ncipollo/release-action@v1.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: 'name'
        body: 'test'
        tag: '0.0.1'
        artifacts: CLEO5.zip