name: CLEO 5 Release Build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'VERSION'

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [GTASA]
        buildtype: [Release]

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build
      shell: cmd
      run: |
        set PLUGIN_SDK_DIR=plugin-sdk
        msbuild -m CLEO5.sln /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
    - name: Prepare archive
      shell: cmd
      run: |
        mkdir .output\Release\cleo
        mkdir .output\Release\cleo\cleo_modules
        mkdir .output\Release\cleo\cleo_plugins
        mkdir .output\Release\cleo\cleo_saves
        mkdir .output\Release\cleo\cleo_text
        mkdir .output\Release\cleo_readme
        copy third-party\bass\bass.dll .output\Release\cleo\bass.dll
        copy CHANGELOG.md .output\Release\cleo_readme\CHANGELOG.md
        copy README.md .output\Release\cleo_readme\README.md
        copy source\cleo_config.ini .output\Release\cleo\.cleo_config.ini
        copy cleo_plugins\.output\*.cleo .output\Release\cleo\cleo_plugins
        copy cleo_plugins\.output\*.ini .output\Release\cleo\cleo_plugins
        
        
        for /f "tokens=*" %%a in (VERSION) do set version=%%a
        echo "current_version=%version%" >> "$GITHUB_ENV"
        echo "release_notes=release" >> "$GITHUB_ENV"

    - name: Pack binaries (Main)
      uses: ThirteenAG/zip-release@master
      with:
        path: ./.output/Release/*
        type: 'zip'
        filename: 'CLEO5.zip'
        exclusions: '*.pdb *.lib *.exp *.map'
    - name: Upload Release
      uses: ncipollo/release-action@v1.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ github.env.current_version }}
        body: ${{ github.env.release_notes }}
        tag: v${{ github.env.current_version }}
        artifacts: CLEO5.zip