name: Test Build

on:
  workflow_dispatch: # manually

  push:
    branches-ignore:
      - master
    
    paths:
      - '**.c*' ## .c and .cpp
      - '**.h*' ## .h and .hpp
      - '**.def'
      - '**.lib'
      - '**.rc'
      - '**.vcproj'
      - '**.vcxproj.filters'
      - '**.sln'

jobs:
  Test_Build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up MsBuild
        uses: microsoft/setup-msbuild@v2

      - name: Tag with current commit SHA
        id: custom_build
        run: node.exe .github/workflows/tag-custom-build.js

      - name: Core - Build
        shell: cmd
        run: |
          @echo off
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
          msbuild CLEO5.sln /property:Configuration=Release /property:Platform=GTASA /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
          node .github/workflows/analyze-build-log.js "Core compilation"

      - name: Core - VirusTotal scan
        id: scan_core
        env:
          vt_key: ${{secrets.VT_KEY}}
        if: ${{env.vt_key != ''}}
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './.output/Release/CLEO.asi'

      - name: Core - VirusTotal log
        if: steps.scan_core.outcome == 'success'
        run: echo "::notice title=CLEO Core virus scan::${{steps.scan_core.outputs.analysis}}"

      - name: Plugins - Build
        shell: cmd
        run: |
          @echo off
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
          msbuild cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86 /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
          node .github/workflows/analyze-build-log.js "Plugins compilation"

      - name: Plugins - VirusTotal scan
        id: scan_plugins
        env:
          vt_key: ${{secrets.VT_KEY}}
        if: ${{env.vt_key != ''}}
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './cleo_plugins/.output/*.cleo'

      - name: Plugins - VirusTotal log
        if: steps.scan_plugins.outcome == 'success'
        run: echo "::notice title=CLEO Core virus scan::${{steps.scan_plugins.outputs.analysis}}"

      - name: Gather output files
        shell: cmd
        run: |
          @echo Create directories
          mkdir .output\Release\cleo
          mkdir .output\Release\cleo\cleo_plugins

          @echo Copy files
          copy source\cleo_config.ini .output\Release\cleo\.cleo_config.ini
          copy cleo_plugins\.output\*.cleo .output\Release\cleo\cleo_plugins
          copy cleo_plugins\.output\*.ini .output\Release\cleo\cleo_plugins

      - name: Upload Result
        id: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: SA.CLEO-v${{steps.custom_build.outputs.version}}-${{steps.custom_build.outputs.sha}}
          path: |
            .output\Release\*
            !.output\Release\*.pdb
            !.output\Release\*.lib
            !.output\Release\*.exp

      - name: Log download link
        run: echo "::notice title=Download this build::${{steps.upload.outputs.artifact-url}}"
